name: Deploy to TMMSoftware

on:
  push:
    branches:
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

  deploy:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "eng.miguelaz+tmmsoftware@gmail.com"
          git config --global user.name "The Mikest Mike"

      - name: Push to Production Repo
        run: |
          git clone https://github.com/TMMSoftware/Gesture-Control-System.git prod_repo
          rsync -av --exclude='.git' ./ prod_repo/
          cd prod_repo
          git add .
          git commit -m "Deploy from release branch: $GITHUB_REF"
          git push https://${{ secrets.TMM_PAT }}@github.com/TMMSoftware/Gesture-Control-System.git main
