name: Sync to TMMSoftware

on:
  push:
    tags:
      - "v*"  # Runs this action whenever a version tag is pushed (e.g., v1.0.0)
  workflow_dispatch:  # Enables manual trigger


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The-Mikest-Mike Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Git Credentials
        run: |
          git config --global user.email "eng.miguelaz+tmmsoftware@gmail.com"
          git config --global user.name "The Mikest Mike"

      - name: Push to TMMSoftware
        run: |
          git clone https://github.com/TMMSoftware/tmmsoftware.github.io.git target_repo
          rsync -av --exclude='.git' ./ target_repo/
          cd target_repo
          git add .
          git commit -m "Auto-sync from The-Mikest-Mike - $GITHUB_REF"
          git push https://${{ secrets.TMM_PAT }}@github.com/TMMSoftware/tmmsoftware.github.io.git main
        env:
          TMM_PAT: ${{ secrets.TMM_PAT }}
